[package]
name = "plug"
version = "0.1.0"
edition = "2024"

[dependencies]
dyn-utils = { version = "0.1.1" }
facet = { version = "0.46.5", default-features = false, features = ["alloc"] }
hazymacros = { version = "0.1.0", path = "../hazymacros" }
inventory = "0.3.24"
konst = { version = "0.4.3", default-features = false, features = ["alloc", "iter"] }
paste = "1.0.15"
