[package]
name = "plug-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "3", features = ["full"] }
syn_derive = "0.2.0"

base64 = { version = "0.23", optional = true }
minicbor-serde = { version = "0.7", features = ["std"], optional = true }
serde = { version = "1", features = ["derive"], optional = true }
getrandom = { version = "0.4.3", features = ["std"], optional = true }
serde_tokenstream = "0.3.0"

[features]
direct = ["dep:serde", "dep:minicbor-serde", "dep:base64", "dep:getrandom"]
